import type { ToolCategoryDefinition } from '../../../types/tool';

export const categoryCatalog: ToolCategoryDefinition[] = [
  {
    id: 'image-tools',
    name: 'Image Tools',
    shortName: 'Images',
    description: 'Convert, optimize, enhance, and transform images with browser-first and AI-ready workflows.',
    iconKey: 'image',
    heroTitle: 'Modern image workflows without friction',
    heroDescription: 'From quick conversions to premium AI enhancements, this category is built for speed and scale.',
    seo: {
      title: 'Image Tools | CrossConvert',
      description: 'Convert and optimize images with modern browser-first tooling and scalable cloud-ready architecture.',
      keywords: ['image tools', 'webp to png', 'png to jpg', 'image compressor'],
    },
  },
  {
    id: 'pdf-tools',
    name: 'PDF Tools',
    shortName: 'PDF',
    description: 'Merge, split, compress, convert, and enhance PDFs through a scalable document processing foundation.',
    iconKey: 'file-text',
    heroTitle: 'Document processing for real workloads',
    heroDescription: 'Prepared for browser tasks today and queue-backed cloud jobs tomorrow.',
    seo: {
      title: 'PDF Tools | CrossConvert',
      description: 'Explore scalable PDF tooling for merge, split, compression, OCR, and more.',
      keywords: ['pdf tools', 'merge pdf', 'split pdf', 'compress pdf'],
    },
  },
  {
    id: 'video-tools',
    name: 'Video Tools',
    shortName: 'Video',
    description: 'Prepare video conversion, compression, trimming, and AI captioning within a future microservice-ready platform.',
    iconKey: 'video',
    heroTitle: 'Video pipelines built for heavy processing',
    heroDescription: 'Designed for future queue workers, chunked uploads, and compute-aware orchestration.',
    seo: {
      title: 'Video Tools | CrossConvert',
      description: 'Scalable video tool architecture for conversions, compression, trimming, and AI captioning.',
      keywords: ['video tools', 'mp4 converter', 'video compressor', 'subtitle generator'],
    },
  },
  {
    id: 'audio-tools',
    name: 'Audio Tools',
    shortName: 'Audio',
    description: 'Convert, clean, compress, and refine audio using a modular processing abstraction.',
    iconKey: 'audio',
    heroTitle: 'Audio tooling prepared for AI cleanup and conversion',
    heroDescription: 'A shared platform contract supports lightweight converters and premium enhancement flows.',
    seo: {
      title: 'Audio Tools | CrossConvert',
      description: 'Audio conversion and cleanup platform ready for compression, denoise, and editing workflows.',
      keywords: ['audio tools', 'mp3 converter', 'wav converter', 'noise removal'],
    },
  },
  {
    id: 'ai-tools',
    name: 'AI Tools',
    shortName: 'AI',
    description: 'Upscaling, background removal, OCR, captioning, and enhancement features prepared for GPU-backed services.',
    iconKey: 'sparkles',
    heroTitle: 'AI utilities with premium-ready architecture',
    heroDescription: 'Built to route between browser UX and cloud inference pipelines as the platform grows.',
    seo: {
      title: 'AI Tools | CrossConvert',
      description: 'Future-ready AI utilities for enhancement, extraction, captioning, and automated workflows.',
      keywords: ['ai tools', 'background remover', 'ocr', 'image enhancer'],
    },
  },
  {
    id: 'developer-tools',
    name: 'Developer Tools',
    shortName: 'Developers',
    description: 'Instant browser-based utilities for formatting, encoding, decoding, testing, and productivity workflows.',
    iconKey: 'code',
    heroTitle: 'Developer utilities inside the same platform',
    heroDescription: 'A unified catalog architecture supports file tools and interactive utilities together.',
    seo: {
      title: 'Developer Tools | CrossConvert',
      description: 'Developer utility pages for JSON, JWT, regex, timestamps, QR, hashes, and more.',
      keywords: ['developer tools', 'json formatter', 'jwt decoder', 'regex tester'],
    },
  },
  {
    id: 'file-utilities',
    name: 'File Utilities',
    shortName: 'Files',
    description: 'Core file workflows, batch actions, packaging, and general-purpose productivity tools.',
    iconKey: 'folder',
    heroTitle: 'Centralized utilities across file workflows',
    heroDescription: 'This category supports cross-cutting helpers, batch actions, and future workspace experiences.',
    seo: {
      title: 'File Utilities | CrossConvert',
      description: 'Scalable file utility architecture for batch workflows and general-purpose file operations.',
      keywords: ['file utilities', 'batch tools', 'file operations'],
    },
  },
];
