export const imageToolIds = [
  'webp-to-png',
  'png-to-jpg',
  'jpg-to-png',
  'jpg-to-webp',
  'png-to-webp',
  'avif-to-png',
  'image-compressor',
  'resize-image',
  'crop-image',
  'rotate-image',
  'watermark-image',
  'remove-background',
  'image-upscaler',
  'image-to-pdf',
  'heic-converter',
  'svg-converter',
  'ico-generator',
  'gif-maker',
  'meme-generator',
] as const;
